ver: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
user_activated: "1"

name_max: 50
email_max: 255
pass_min: 6
gravatar_size: 80
gravatar_user_size: 50
gravatar_follow_size: 30
paginate_per: 10
time_pass_reset: 2
content_max: 140

author: Michael Hartl

news_link: http://news.railstutorial.org/
rails_link: http://rubyonrails.org/
rails_tut_link: https://www.railstutorial.org/
rails_help_link: https://www.railstutorial.org/help
rails_book_link: https://www.railstutorial.org/book
rails_contact_link: https://www.railstutorial.org/contact
rails_screencasts_link: http://screencasts.railstutorial.org/
author_link: http://www.michaelhartl.com/
gravatar_link: http://gravatar.com/emails
